### ISSUE TITLE
CSS并不简单--走进border、box-shadow和outline

### ISSUE THREAD

**Issue by 15751165579** [15751165579/Blog#1]
> 这篇文章主要介绍标题中三个属性独特的一面。不独特你打我）:

#### 一、border
&emsp;&emsp;其实对于border,想必大家已经了解很多了。所以我就不啰嗦太多的基本东西。

&emsp;&emsp;比如border-radius我们只需要看这张图:
<center>![image](https://user-gold-cdn.xitu.io/2017/5/19/a7dc1c4612749412a1d6f2337ee13af0)</center>

&emsp;&emsp;现在我们来看看border的真实面貌：
```css
	width: 0;
    height: 0;
    border: 30px solid transparent;
	border-top-color: rgb(222,11,22);
    border-left-color: rgb(20,100,200);
    border-right-color: rgb(1,200,200);
    border-bottom-color: rgb(100,20,200);
```  
<center>![image](https://user-gold-cdn.xitu.io/2017/5/19/36222ddacab011c2d1db89f3a1929d5f)</center>

&emsp;&emsp;利用这一点我们能做出什么呢？微信的消息框：
<center>![image](https://user-gold-cdn.xitu.io/2017/5/19/784c77a2434cd87e920cfb326e6e40a8)</center>

```css
	.item {
    	position: relative;
        width: 150px;
        height: 50px;
        background: #fff;
        border-radius: 5px;
        line-height: 50px;
        &::after {
    	    content: "";
            display: block;
            position: absolute;
            width: 0;
            height: 0;
            border: 10px solid transparent;
            border-right-color: #fff;
            top: 15px;
            left: -20px;
        }
    }
```

&emsp;&emsp;你看看以后再遇到用小三角的，是不是so easy! 哪怕是要用两个。可能讲到这里，不少同学就很不乐意了，这些明明我多懂。来个新鲜的行不行？客官往下看：
<center>![image](https://user-gold-cdn.xitu.io/2017/5/19/02594e2e7c38d73e6f578c7bd6a706c7)</center>

&emsp;&emsp;what?别告诉我这也是用border画的！心细的同学应该会看出来，这不就是dashed的样式吗？的确是用了dashed，但是我们多知道dashed这个样式，我们不能修改它虚线的间距，这点很头疼。所以这里这个图案出现的有那么一点碰巧，但是它揭露了背景颜色会渗透到border的下面。

&emsp;&emsp;所以，当你要实现一个半透明的边框时，并不是一个容易的事，你还需要结合background-clip。

&emsp;&emsp;聪明的同学又要问了，你这个图案实现的太巧合了，在很多情况下，dashed并不能像我们预期的那样。哈哈。接下来从box-shadow的讲解中，我会给你个十全十美的方案。

#### 二、box-shadow
&emsp;&emsp;这里我就不说什么单边阴影，双边阴影了。直接接着上面的话题吧。要实现上面的图案，首先你要明白，box-shadow是支持逗号分隔语法的。不卖关子，看代码:
```css
	width: 100px;
    height: 100px;
    background: rgb(200,100,200);
    box-shadow: 40px 0 0 -20px rgb(200,100,200),
                -40px 0 0 -20px rgb(200,100,200),
                0 40px 0 -20px rgb(200,100,200),
                0 -40px 0 -20px rgb(200,100,200);
```
&emsp;&emsp;我靠！阴影的尺寸还能是负数，是不是很惊讶。实际上，当阴影为负数时，阴影向内扩散，是不是很神奇，是不是很完美。

&emsp;&emsp;这里我们还可以利用box-shadow来制造图片翘边的效果，这里我们要结合transform。
<center>![image](https://user-gold-cdn.xitu.io/2017/5/19/b39330a9f512bed1639bf434260f5fec)</center>

```css
	.item {
	    position: relative;
        width: 240px;
        height: 320px;
        background: url(../assets/images/head.jpeg) no-repeat center / 240px 320px;
        border: 5px solid #fff;
        &::before {
    	    content: "";
            display: block;
            position: absolute;
            top: 150px;
            left: 70px;
            width: 150px;
            height: 150px;
            box-shadow: 5px 5px 15px 10px rgb(213,213,213);
            transform: skewX(20deg) rotate(15deg);
            z-index: -100;
        }
    
        &::after {
    	    content: "";
            display: block;
            position: absolute;
            top: 18px;
            left: 12px;
            width: 150px;
            height: 150px;
            box-shadow: 0 0 15px 10px rgba(0,0,0,.2);
            transform: skewX(20deg) rotate(15deg);
            z-index: -100;
        }
	}
```
&emsp;&emsp;这里我们要记住一点，无论你用box-shadow像外扩展了多少，并不影响元素本身的大小。

#### 三、outline
&emsp;&emsp;与box-shadow相似的是，它的大小也不影响元素的大小。这里可能需要讲的，就是不要忽略outline-offset，而且它可以取负值。

```css
	.item {
    	width: 100px;
        height: 100px;
        outline: 10px solid rgb(110,110,110);
        outline-offset: -45px;
        border: 10px solid rgb(110,110,110);
        border-radius: 50%;
    }
```

<center>![image](https://user-gold-cdn.xitu.io/2017/5/19/ee68918076b6283cffe53a008f346cd5)</center>

***

&nbsp;&nbsp;喜欢本文的小伙伴们,欢迎关注我的订阅号**超爱敲代码**,查看更多内容.
![](https://user-gold-cdn.xitu.io/2018/7/16/164a35f54e4bf38a?w=258&h=258&f=jpeg&s=26776)
